if(document.head.id=="SignupPage"){
 define(['signup','jquery-3.6.0']) 
}
if(document.head.id=="LoginPage"){
 define(['login','jquery-3.6.0']) 
}
if(document.head.id=="IndexPage"){
  define(['index'])
}
if(document.head.id=="TestPage"){
  define(['test','jquery-3.6.0'])
}